# Generated by Django 6.0.7 on 2026-07-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='邀请码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='最大使用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
        ),
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='可选姓名')),
                ('is_taken', models.BooleanField(default=False, verbose_name='是否已被注册')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, unique=True, verbose_name='显示姓名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('face_token', models.CharField(blank=True, max_length=100, verbose_name='百度人脸token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
