# Generated by Django 6.0.7 on 2026-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classphoto',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='classphoto',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
    ]
