# Generated by Django 6.0.7 on 2026-07-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_alter_classphoto_options_classphoto_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_bg/', verbose_name='个人空间背景'),
        ),
    ]
