# Generated by Django 6.0.7 on 2026-07-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_profile_global_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_videos/'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
