# Generated by Django 6.0.7 on 2026-07-26 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '相册', 'verbose_name_plural': '相册'},
        ),
        migrations.AlterModelOptions(
            name='classphoto',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '班级合照', 'verbose_name_plural': '班级合照'},
        ),
        migrations.AlterModelOptions(
            name='correctionrequest',
            options={'verbose_name': '修正请求', 'verbose_name_plural': '修正请求'},
        ),
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'verbose_name': '事件照片/视频', 'verbose_name_plural': '事件照片/视频'},
        ),
        migrations.AlterModelOptions(
            name='facehotzone',
            options={'ordering': ['y', 'x'], 'verbose_name': '人脸热区', 'verbose_name_plural': '人脸热区'},
        ),
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': '邀请码', 'verbose_name_plural': '邀请码'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='pendingregistration',
            options={'verbose_name': '花名册', 'verbose_name_plural': '花名册'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': '照片/视频', 'verbose_name_plural': '照片/视频'},
        ),
        migrations.AlterModelOptions(
            name='photofacemapping',
            options={'verbose_name': '照片人脸映射', 'verbose_name_plural': '照片人脸映射'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '个人档案', 'verbose_name_plural': '个人档案'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '站点设置', 'verbose_name_plural': '站点设置'},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'verbose_name': '时间线事件', 'verbose_name_plural': '时间线事件'},
        ),
        migrations.AddField(
            model_name='photo',
            name='message',
            field=models.CharField(blank=True, max_length=500, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=100, verbose_name='相册名称'),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='memories.profile', verbose_name='所有者'),
        ),
        migrations.AlterField(
            model_name='classphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classphoto',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='classphoto',
            name='image',
            field=models.ImageField(upload_to='class_photos/', verbose_name='合照图片'),
        ),
        migrations.AlterField(
            model_name='classphoto',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='current_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_corrections', to='memories.profile', verbose_name='当前归属'),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='是否已处理'),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='memories.photo', verbose_name='目标照片'),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='memories.profile', verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='correctionrequest',
            name='suggested_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_corrections', to='memories.profile', verbose_name='建议改为'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memories.timelineevent', verbose_name='所属事件'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.profile', verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='facehotzone',
            name='height',
            field=models.FloatField(help_text='高度（百分比）', verbose_name='高度%'),
        ),
        migrations.AlterField(
            model_name='facehotzone',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotzones', to='memories.classphoto', verbose_name='所属合照'),
        ),
        migrations.AlterField(
            model_name='facehotzone',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotzones', to='memories.profile', verbose_name='关联同学'),
        ),
        migrations.AlterField(
            model_name='facehotzone',
            name='width',
            field=models.FloatField(help_text='宽度（百分比）', verbose_name='宽度%'),
        ),
        migrations.AlterField(
            model_name='facehotzone',
            name='x',
            field=models.FloatField(help_text='X 坐标（百分比）', verbose_name='X坐标%'),
        ),
        migrations.AlterField(
            model_name='facehotzone',
            name='y',
            field=models.FloatField(help_text='Y 坐标（百分比）', verbose_name='Y坐标%'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='最大使用次数'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='已使用次数'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('correction', '修正请求'), ('face_match', '人脸匹配'), ('event_photo', '事件新照片'), ('public_photo', '公开照片'), ('event_created', '新事件')], max_length=20, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='关联链接'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='memories.profile', verbose_name='发送者'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='是否已注册'),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memories.album', verbose_name='所属相册'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to='memories.profile', verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='user_videos/', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='height',
            field=models.FloatField(verbose_name='高度%'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='is_auto_matched',
            field=models.BooleanField(default=False, verbose_name='是否自动匹配'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_mappings', to='memories.photo', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='face_mappings', to='memories.profile', verbose_name='匹配同学'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='width',
            field=models.FloatField(verbose_name='宽度%'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='x',
            field=models.FloatField(verbose_name='X坐标%'),
        ),
        migrations.AlterField(
            model_name='photofacemapping',
            name='y',
            field=models.FloatField(verbose_name='Y坐标%'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='显示名称'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='face_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='人脸标识'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='图片值'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='设置键名'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='文本值'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.profile', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_date',
            field=models.DateField(verbose_name='事件日期'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='已审核'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
