# Generated by Django 6.0.7 on 2026-07-27 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0010_alter_album_options_alter_classphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facehotzone',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotzones', to='memories.pendingregistration', verbose_name='关联同学'),
        ),
    ]
