# Generated by Django 6.0.7 on 2026-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0011_alter_facehotzone_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='详细描述（可被搜索）'),
        ),
        migrations.AddField(
            model_name='photo',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览次数'),
        ),
    ]
