# Generated by Django 6.0.7 on 2026-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0012_photo_description_photo_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('personal', '个人相册'), ('shared', '共同相册')], default='personal', max_length=10, verbose_name='相册类型'),
        ),
    ]
