# Generated by Django 6.0.7 on 2026-07-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0013_album_album_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('detail', models.CharField(max_length=500, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memories.profile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '行为日志',
                'verbose_name_plural': '行为日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
