# Generated by Django 6.0.7 on 2026-07-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0015_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTrainingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_training/', verbose_name='训练照片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_registered', models.BooleanField(default=False, verbose_name='已注册到百度')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_photos', to='memories.profile', verbose_name='所属同学')),
            ],
            options={
                'verbose_name': '人脸训练库',
                'verbose_name_plural': '人脸训练库',
            },
        ),
    ]
