# Generated by Django 6.0.7 on 2026-07-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0016_facetrainingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除（软删除）'),
        ),
    ]
