# Generated by Django 6.0.7 on 2026-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0017_album_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visibility',
            field=models.CharField(choices=[('all', '全部人可见'), ('target', '仅对方可见'), ('selected', '部分人可见')], default='all', max_length=10, verbose_name='可见范围'),
        ),
        migrations.AddField(
            model_name='photo',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_photos', to='memories.profile', verbose_name='指定可见的人'),
        ),
    ]
