# Generated by Django 6.0.7 on 2026-07-30 15:31

from django.db import migrations


def add_roster_names(apps, schema_editor):
    PendingRegistration = apps.get_model('memories', 'PendingRegistration')
    names = [
        '王柯松', '代红平', '丁朵', '曹婷婷', '杨凤科', '胡红伟',
        '刘兴旺', '白育荣', '张延涛', '包书红', '姚学颖', '杨庆科',
        '许土一', '郭军喜', '任秀册', '张金梅', '贠涛', '闫立军',
    ]
    existing = set(PendingRegistration.objects.values_list('name', flat=True))
    for name in names:
        if name not in existing:
            PendingRegistration.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0018_photo_visibility_photo_visible_to'),
    ]

    operations = [
        migrations.RunPython(add_roster_names, migrations.RunPython.noop),
    ]
