# Generated by Django 6.0.7 on 2026-07-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0020_remove_roster_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='related_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memories.photo', verbose_name='关联照片'),
        ),
    ]
