# Generated by Django 6.0.7 on 2026-07-31 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0022_cleanup_empty_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['-event_date', '-created_at'], 'verbose_name': '时间线事件', 'verbose_name_plural': '时间线事件'},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(choices=[('free', '自由留言'), ('feedback', '问题反馈')], default='free', max_length=10, verbose_name='留言类型')),
                ('content', models.TextField(max_length=2000, verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/', verbose_name='附图')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已解决')], default='open', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='memories.profile', verbose_name='留言者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='memories.message', verbose_name='回复目标')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'ordering': ['-created_at'],
            },
        ),
    ]
