# Generated by Django 6.0.7 on 2026-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0023_alter_timelineevent_options_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingregistration',
            options={'ordering': ['pinyin_key'], 'verbose_name': '花名册', 'verbose_name_plural': '花名册'},
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='pinyin_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='拼音排序键'),
        ),
    ]
