# Generated by Django 6.0.7 on 2026-07-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0025_populate_pinyin_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_albums', to='memories.profile', verbose_name='创建者'),
        ),
    ]
